### ISSUE TITLE
Python3 ModuleNotFoundError: No module named 'graph'

### ISSUE THREAD

**Issue by rhzs** [complexdb/zincbase#4]
Hi,

I stumbled upon module not found error in MacOS 10.14.3 (Mojave). 

I have tried to install graph-tools in python3 and graph-tool deps via Homebrew.

```
❯ python3 examples/countries.py
Traceback (most recent call last):
  File "examples/countries.py", line 8, in <module>
    from zincbase import KB
  File "/usr/local/lib/python3.7/site-packages/zincbase/__init__.py", line 1, in <module>
    from .zincbase import KB
  File "/usr/local/lib/python3.7/site-packages/zincbase/zincbase.py", line 20, in <module>
    from graph import Node
ModuleNotFoundError: No module named 'graph'
```

Any idea how to make it work?

**Comment by kartik7511** [comment]
Have you cloned the repository? the graph module is there in repository.

**Comment by rhzs** [comment]
Yes, I did, cloned the repo

**Comment by tomgrek** [comment]
Hi, I managed to break the module packaging then go on holiday. Sorry! Everything should work now either via `pip install` or `git clone`.
